### PR TITLE
Prevent electing bosses for lobbies with more than one player.

### PR DESCRIPTION
**Pull request by DeviousNull**
### **This PR is a significant change to player-facing functionality, and should not be deployed without an accompanying announcement!**
_(I'll write up a proposed announcement tomorrow, but this can be reviewed for now at least)_
_(Also, https://github.com/beyond-all-reason/teiserver/pull/382 and https://github.com/beyond-all-reason/spads_config_bar/pull/137 should be merged/deployed before this PR)_

This patch makes two changes:

First, logic is added to `preSpadsCommand()` which blocks commands of the form "!callvote boss USERNAME" when:
- There is more than one **player** in the lobby
- AND, the caller has accessLevel < 100 (not a boss/mod/admin)

(Note that SPADS implicitly converts "!boss ..." to "!callvote boss ..." when the caller is low-privileged.)

Second, spectators with accessLevel 100 (already a boss) are permitted to use the "!boss" command. This makes it more convenient to transfer boss privileges to another player.

### CODE REVIEW

**Comment by Beherith** [comment]
Doesnt this explicitly prevent _any_ boss votes even if there are no bosses?

**Comment by Beherith** [comment]
Hmm, so the solution when unhappy with boss (or boss is AFK) is just "make new room"?

**Comment by Beherith** [comment]
Based on this exact description:
https://server4.beyondallreason.info/microblog/show/37

in commands_custom.conf:
```
[boss](voteTime:60,majorityVoteMargin:25)
battle:player,playing:|100:10
::|130:
```

And in commands_default.conf:
```
[boss](voteTime:60,majorityVoteMargin:25)
battle:player,playing:|100:0
::|130:
```
Which, according to my interpretation means that bosses can be removed from non-custom(default team, ffa, duel) games by a 75% majority.

**Comment by Beherith** [comment]
Okies, is there a relevant microblog post that we could link into chobby when this goes live?

**Comment by Beherith** [comment]
Merging into Integration for testing

**Comment by PtaQQ** [comment]
Just notifying I am back from vacation and ready to push the announcements if you are ready :) @Beherith @DeviousNull

**Pull request merged**
